### ISSUE TITLE
Failed test with latest IM 6.9.10-69

### ISSUE THREAD

**Issue by remicollet** [Imagick/imagick#301]
```
TEST 97/275 [tests/097_Imagick_newPseudoImage_basic.phpt]
========DIFF========
001+ Fatal error: Uncaught ImagickException: unrecognized color `' @ warning/color.c/QueryMagickColorCompliance/2621 in /dev/shm/BUILD/php-pecl-imagick-3.4.4/NTS/tests/097_Imagick_newPseudoImage_basic.php:7
001- Ok
002+ Stack trace:
003+ #0 /dev/shm/BUILD/php-pecl-imagick-3.4.4/NTS/tests/097_Imagick_newPseudoImage_basic.php(7): Imagick->newpseudoimage(300, 300, 'gradient:')
004+ #1 /dev/shm/BUILD/php-pecl-imagick-3.4.4/NTS/tests/097_Imagick_newPseudoImage_basic.php(13): newPseudoImage('gradient:')
005+ #2 {main}
006+   thrown in /dev/shm/BUILD/php-pecl-imagick-3.4.4/NTS/tests/097_Imagick_newPseudoImage_basic.php on line 7
========DONE========
FAIL Test Imagick, newPseudoImage [tests/097_Imagick_newPseudoImage_basic.phpt] 

```

**Comment by remicollet** [comment]
Can be related to https://github.com/ImageMagick/ImageMagick6/commit/03a9bac3ba9f51cc107484536738c336b69d7d6b#diff-b48c4feab32724d54e6e77845f23f7cc
