### ISSUE TITLE
166_Imagick_waveImage_basic test fail on x86 

### ISSUE THREAD

**Issue by andypost** [Imagick/imagick#385]
Used to rebuild extension with imagemagick 7.0.11-1 and 7.0.11-3 on Alpinelinux but got a failed test (only x86 32-bits)

The failure is the same for PHP 7 and 8 and looks related to cache somehow

https://github.com/ImageMagick/ImageMagick/blob/f7e785915f626301355319102cf146f8fe5240c0/MagickCore/cache.c#L5053-L5061

```
001+ Fatal error: Uncaught ImagickException: width or height exceeds limit `logo[0]' @ error/cache.c/SetPixelCacheNexusPixels/5058 in /builds/TBK/aports/community/php7-pecl-imagick/src/imagick-3.4.4/tests/166_Imagick_waveImage_basic.php:9
001- Ok
002+ Stack trace:
003+ #0 /builds/TBK/aports/community/php7-pecl-imagick/src/imagick-3.4.4/tests/166_Imagick_waveImage_basic.php(9): Imagick->waveimage(5, 20)
004+ #1 /builds/TBK/aports/community/php7-pecl-imagick/src/imagick-3.4.4/tests/166_Imagick_waveImage_basic.php(14): waveImage(5, 20)
005+ #2 {main}
006+   thrown in /builds/TBK/aports/community/php7-pecl-imagick/src/imagick-3.4.4/tests/166_Imagick_waveImage_basic.php on line 9

and php 8

001+ Fatal error: Uncaught ImagickException: width or height exceeds limit `logo[0]' @ error/cache.c/SetPixelCacheNexusPixels/5058 in /builds/TBK/aports/community/php8-pecl-imagick/src/imagick-765649716faf3215b6ffca1b329e6a49aa42b24f/tests/166_Imagick_waveImage_basic.php:9
001- Ok
002+ Stack trace:
003+ #0 /builds/TBK/aports/community/php8-pecl-imagick/src/imagick-765649716faf3215b6ffca1b329e6a49aa42b24f/tests/166_Imagick_waveImage_basic.php(9): Imagick->waveimage(5, 20)
004+ #1 /builds/TBK/aports/community/php8-pecl-imagick/src/imagick-765649716faf3215b6ffca1b329e6a49aa42b24f/tests/166_Imagick_waveImage_basic.php(14): waveImage(5, 20)
005+ #2 {main}
006+   thrown in /builds/TBK/aports/community/php8-pecl-imagick/src/imagick-765649716faf3215b6ffca1b329e6a49aa42b24f/tests/166_Imagick_waveImage_basic.php on line 9
========DONE========
FAIL Test Imagick, waveImage [tests/166_Imagick_waveImage_basic.phpt] 
```

**Comment by andypost** [comment]
Ref https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/19196

**Comment by Danack** [comment]
Hi @andypost,

I don't really support [Imagick on Alpine](https://github.com/Imagick/imagick/issues/328) for reasons.

If you want me to take a look, please can you submit a PR with a container that gets everything setup, and also with the package 'strace' installed.

**Comment by Danack** [comment]
Closing. Although I'm not going to block people using Imagick on Alpine, I'm also not going to spend significant amounts of time supporting it.

**Comment by bukka** [comment]
@andypost Is this still an issue?

**Comment by andypost** [comment]
@bukka arm was fixed via https://github.com/ImageMagick/ImageMagick/commit/b7baa4e419c2316de4a7d01e4cf794992f74598f
